#ifndef ATOMS_H_
#define ATOMS_H_

#include <erl_nif.h>

extern ERL_NIF_TERM
  ETDB_ATOM_OK,
  ETDB_ATOM_ERROR,
  ETDB_ATOM_TRUE,
  ETDB_ATOM_FALSE,
  ETDB_ATOM_ENIF_GET_STRING,
  ETDB_ATOM_MEMORY,
  ETDB_ATOM_INVALID_ARGS,
  ETDB_ATOM_NOT_FOUND,
  ETDB_ATOM_IO,
  ETDB_ATOM_CORRUPTION,
  ETDB_ATOM_EXISTS,
  ETDB_ATOM_CONFLICT,
  ETDB_ATOM_TOO_LARGE,
  ETDB_ATOM_MEMORY_LIMIT,
  ETDB_ATOM_INVALID_DB,
  ETDB_ATOM_UNKNOWN,
  ETDB_ATOM_LOCKED,
  ETDB_ATOM_UNKNOWN_ERROR_CODE;


void etdb_make_atoms(ErlNifEnv *env);

#endif // ATOMS_H_
